// components/budget-particulars.tsx
"use client"

import { useState } from "react"
import { useBudget } from "@/lib/budget-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog"
import { Plus, Pencil, Trash2 } from "lucide-react"

export function BudgetParticulars() {
  const { categories, departments, particulars, addParticular, updateParticular, deleteParticular } = useBudget()
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editId, setEditId] = useState<string | null>(null)
  const [categoryId, setCategoryId] = useState("")
  const [departmentId, setDepartmentId] = useState("")
  const [accountCode, setAccountCode] = useState("")
  const [accountName, setAccountName] = useState("")
  const [particular, setParticular] = useState("")
  const [description, setDescription] = useState("")
  const [filterCategory, setFilterCategory] = useState("all")
  const [filterDepartment, setFilterDepartment] = useState("all")
  const [searchQuery, setSearchQuery] = useState("")

  const filtered = particulars.filter((p) => {
    const matchCat = filterCategory === "all" || p.categoryId === filterCategory
    const matchDept = filterDepartment === "all" || p.departmentId === filterDepartment
    const matchSearch =
      p.particular.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.accountCode.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.accountName.toLowerCase().includes(searchQuery.toLowerCase())
    return matchCat && matchDept && matchSearch
  })

  function getCategoryName(id: string) {
    return categories.find((c) => c.id === id)?.name || "Unknown"
  }

  function getDepartmentName(id: string) {
    return departments.find((d) => d.id === id)?.name || "Unknown"
  }

  function openNew() {
    setEditId(null)
    setCategoryId("")
    setDepartmentId("")
    setAccountCode("")
    setAccountName("")
    setParticular("")
    setDescription("")
    setDialogOpen(true)
  }

  function openEdit(id: string) {
    const par = particulars.find((p) => p.id === id)
    if (!par) return
    setEditId(id)
    setCategoryId(par.categoryId)
    setDepartmentId(par.departmentId)
    setAccountCode(par.accountCode)
    setAccountName(par.accountName)
    setParticular(par.particular)
    setDescription(par.description)
    setDialogOpen(true)
  }

  function handleSave() {
    if (!categoryId || !departmentId || !particular.trim()) return
    const data = {
      categoryId,
      departmentId,
      accountCode: accountCode.trim(),
      accountName: accountName.trim(),
      particular: particular.trim(),
      description: description.trim(),
    }
    if (editId) {
      updateParticular(editId, data)
    } else {
      addParticular(data)
    }
    setDialogOpen(false)
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h3 className="text-lg font-bold text-[#1a2744]">Budget Particulars</h3>
          <p className="text-sm text-muted-foreground">Manage budget line items by responsibility center</p>
        </div>
        <Button onClick={openNew} size="sm" className="bg-[#1a2744] text-white hover:bg-[#243352]">
          <Plus className="mr-1.5 h-4 w-4" />
          New Particular
        </Button>
      </div>

      <div className="flex flex-col gap-2 sm:flex-row">
        <Select value={filterCategory} onValueChange={setFilterCategory}>
          <SelectTrigger className="w-56">
            <SelectValue placeholder="Filter by category" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Categories</SelectItem>
            {categories.map((cat) => (
              <SelectItem key={cat.id} value={cat.id}>{cat.name}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={filterDepartment} onValueChange={setFilterDepartment}>
          <SelectTrigger className="w-56">
            <SelectValue placeholder="Filter by department" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Departments</SelectItem>
            {departments.map((dept) => (
              <SelectItem key={dept.id} value={dept.id}>{dept.name}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Input
          placeholder="Search particulars..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-64"
        />
      </div>

      <div className="rounded border border-border overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow className="bg-[#1a2744]">
              <TableHead className="font-semibold text-white">Category</TableHead>
              <TableHead className="font-semibold text-white">Responsibility Center</TableHead>
              <TableHead className="font-semibold text-white">Account</TableHead>
              <TableHead className="font-semibold text-white">Particular</TableHead>
              <TableHead className="font-semibold text-white">Description</TableHead>
              <TableHead className="w-24 text-center font-semibold text-white">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filtered.length === 0 ? (
              <TableRow>
                <TableCell colSpan={6} className="py-8 text-center text-muted-foreground">
                  No particulars found
                </TableCell>
              </TableRow>
            ) : (
              filtered.map((par, idx) => (
                <TableRow key={par.id} className={idx % 2 === 0 ? "bg-card" : "bg-muted/30"}>
                  <TableCell className="font-medium text-[#1a2744]">{getCategoryName(par.categoryId)}</TableCell>
                  <TableCell className="text-[#1a2744]">{getDepartmentName(par.departmentId)}</TableCell>
                  <TableCell>
                    <div>
                      <p className="text-sm font-mono text-[#1a2744]">{par.accountCode}</p>
                      <p className="text-xs text-muted-foreground">{par.accountName}</p>
                    </div>
                  </TableCell>
                  <TableCell className="text-[#1a2744]">{par.particular}</TableCell>
                  <TableCell className="text-muted-foreground">{par.description}</TableCell>
                  <TableCell>
                    <div className="flex items-center justify-center gap-1">
                      <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => openEdit(par.id)}>
                        <Pencil className="h-3.5 w-3.5" />
                        <span className="sr-only">Edit</span>
                      </Button>
                      <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive hover:text-destructive" onClick={() => deleteParticular(par.id)}>
                        <Trash2 className="h-3.5 w-3.5" />
                        <span className="sr-only">Delete</span>
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
        <div className="border-t border-border bg-muted/50 px-4 py-2 text-sm text-muted-foreground">
          Total Records: {filtered.length}
        </div>
      </div>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="text-[#1a2744]">{editId ? "Edit Particular" : "New Budget Particular"}</DialogTitle>
            <DialogDescription>
              {editId ? "Update the particular details." : "Add a new budget particular with responsibility center."}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="space-y-2">
              <Label>Category</Label>
              <Select value={categoryId} onValueChange={setCategoryId}>
                <SelectTrigger><SelectValue placeholder="Select a category" /></SelectTrigger>
                <SelectContent>
                  {categories.map((cat) => (
                    <SelectItem key={cat.id} value={cat.id}>{cat.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Responsibility Center / Department</Label>
              <Select value={departmentId} onValueChange={setDepartmentId}>
                <SelectTrigger><SelectValue placeholder="Select department" /></SelectTrigger>
                <SelectContent>
                  {departments.map((dept) => (
                    <SelectItem key={dept.id} value={dept.id}>{dept.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="acct-code">Account Code</Label>
                <Input id="acct-code" value={accountCode} onChange={(e) => setAccountCode(e.target.value)} placeholder="e.g. 4-1005" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="acct-name">Account Name</Label>
                <Input id="acct-name" value={accountName} onChange={(e) => setAccountName(e.target.value)} placeholder="e.g. College - Information System" />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="par-name">Particular</Label>
              <Input id="par-name" value={particular} onChange={(e) => setParticular(e.target.value)} placeholder="e.g. IT Operations" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="par-desc">Description</Label>
              <Input id="par-desc" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Brief description" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
            <Button onClick={handleSave} className="bg-[#1a2744] text-white hover:bg-[#243352]">{editId ? "Update" : "Create"}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// resources/js/Pages/BudgetParticulars/Index.vue
<script setup>
import AppLayout from '@/Layouts/AppLayout.vue'
import Modal from '@/Components/Modal.vue'
import { Head, useForm, router, usePage } from '@inertiajs/vue3'
import { ref, computed } from 'vue'

const perms = computed(() => usePage().props.permissions || {})

const props = defineProps({
    particulars: Array,
    accountTitles: Array,
    categories: Array,
    departments: Array
})

const listData = computed(() => props.accountTitles || props.particulars || [])
const showModal = ref(false)
const editing = ref(null)
const form = useForm({ category_id: '', department_id: '', account_code: '', account_name: '', particular: '', description: '' })

const filterCategory = ref('')
const filterDepartment = ref('')
const searchQuery = ref('')

const filteredParticulars = computed(() => {
    return listData.value.filter(p => {
        const matchCategory = filterCategory.value ? p.category_id === filterCategory.value : true
        const matchDepartment = filterDepartment.value ? p.department_id === filterDepartment.value : true
        const matchSearch = searchQuery.value ?
            (p.particular.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
             p.account_code.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
             p.account_name.toLowerCase().includes(searchQuery.value.toLowerCase())) : true
        return matchCategory && matchDepartment && matchSearch
    })
})

function openCreate() { form.reset(); editing.value = null; showModal.value = true }
function openEdit(p) {
    Object.assign(form, { category_id: p.category_id, department_id: p.department_id, account_code: p.account_code, account_name: p.account_name, particular: p.particular, description: p.description || '' })
    editing.value = p.id; showModal.value = true
}
function save() {
    if (editing.value) form.put(`/budget-particulars/${editing.value}`, { onSuccess: () => { showModal.value = false } })
    else form.post('/budget-particulars', { onSuccess: () => { showModal.value = false } })
}
function remove(id) { if (confirm('Are you sure you want to delete this Account Title?')) router.delete(`/budget-particulars/${id}`) }
</script>

<template>
<Head title="Account Titles" />
<AppLayout>
    <div class="flex items-center justify-between mb-6">
        <div>
            <h2 class="text-xl font-bold text-gray-900">Account Titles</h2>
            <p class="text-sm text-gray-500">Manage budget account titles, line items, and codes</p>
        </div>
        <button v-if="perms.canManageBudget" @click="openCreate" class="rounded-lg bg-navy-dark px-4 py-2.5 text-sm font-semibold text-white hover:bg-navy transition shadow-sm">
            Add Account Title
        </button>
    </div>
    <div class="flex flex-col sm:flex-row gap-4 mb-6">
        <select v-model="filterCategory" class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm text-gray-700 min-w-[200px] shadow-sm">
            <option value="">All Categories</option>
            <option v-for="c in categories" :key="c.id" :value="c.id">{{ c.name }}</option>
        </select>
        <select v-model="filterDepartment" class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm text-gray-700 min-w-[200px] shadow-sm">
            <option value="">All Responsibility Centers</option>
            <option v-for="d in departments" :key="d.id" :value="d.id">{{ d.name }}</option>
        </select>
        <input v-model="searchQuery" type="text" placeholder="Search account title or code..." class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm w-full max-w-sm shadow-sm" />
    </div>

    <div class="rounded-lg bg-white shadow-sm border border-gray-200 overflow-hidden">
        <div class="overflow-x-auto w-full pb-4">
            <table class="w-full text-sm min-w-max whitespace-nowrap">
                <thead>
                    <tr class="bg-navy-dark text-white border-b-2 border-mustard">
                        <th class="px-6 py-4 text-left font-bold text-sm tracking-wide">Category</th>
                        <th class="px-6 py-4 text-left font-bold text-sm tracking-wide">Responsibility Center</th>
                        <th class="px-6 py-4 text-left font-bold text-sm tracking-wide">Account Code</th>
                        <th class="px-6 py-4 text-left font-bold text-sm tracking-wide">Account Title</th>
                        <th class="px-6 py-4 text-left font-bold text-sm tracking-wide">Description</th>
                        <th v-if="perms.canManageBudget" class="px-6 py-4 text-center font-bold text-sm tracking-wide">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="p in filteredParticulars" :key="p.id" class="border-b border-gray-100 hover:bg-gray-50/50 transition-colors">
                        <td class="px-6 py-4 text-gray-800 text-sm align-middle">{{ p.category?.name }}</td>
                        <td class="px-6 py-4 text-gray-800 text-sm align-middle">{{ p.department?.name || p.department?.code }}</td>
                        <td class="px-6 py-4 align-middle">
                            <span class="font-mono text-xs font-semibold px-2 py-1 bg-gray-100 text-gray-800 rounded">{{ p.account_code }}</span>
                            <div class="text-[11px] text-gray-500 mt-0.5 max-w-[200px] whitespace-normal">{{ p.account_name }}</div>
                        </td>
                        <td class="px-6 py-4 text-gray-900 font-medium text-sm align-middle">{{ p.particular }}</td>
                        <td class="px-6 py-4 text-gray-500 text-sm align-middle whitespace-normal max-w-xs">{{ p.description || '-' }}</td>
                        <td v-if="perms.canManageBudget" class="px-6 py-4 text-center align-middle">
                            <div class="inline-flex items-center gap-2">
                                <button @click="openEdit(p)" class="px-3 py-1.5 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 rounded-md text-xs font-semibold shadow-sm transition-all duration-150 border border-indigo-200">
                                    Edit
                                </button>
                                <button @click="remove(p.id)" class="px-3 py-1.5 bg-rose-50 text-rose-700 hover:bg-rose-100 rounded-md text-xs font-semibold shadow-sm transition-all duration-150 border border-rose-200">
                                    Delete
                                </button>
                            </div>
                        </td>
                    </tr>
                    <tr v-if="filteredParticulars.length === 0">
                        <td colspan="6" class="px-6 py-8 text-center text-sm text-gray-500">No account titles found.</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="px-6 py-3 bg-gray-50 text-xs text-gray-500 border-t">Total Records: {{ filteredParticulars.length }}</div>
    </div>

    <Modal :show="showModal" :title="editing ? 'Edit Account Title' : 'Add Account Title'" :subtitle="editing ? 'Update account title details.' : 'Create a new account title line item.'" max-width="lg" @close="showModal = false">
        <form @submit.prevent="save">
            <div class="grid gap-4 sm:grid-cols-2">
                <div><label class="block text-sm font-medium text-gray-700 mb-1.5">Category</label><select v-model="form.category_id" class="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" required><option value="">Select Category</option><option v-for="c in categories" :key="c.id" :value="c.id">{{ c.name }}</option></select></div>
                <div><label class="block text-sm font-medium text-gray-700 mb-1.5">Responsibility Center</label><select v-model="form.department_id" class="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" required><option value="">Select Responsibility Center</option><option v-for="d in departments" :key="d.id" :value="d.id">{{ d.name }}</option></select></div>
                <div><label class="block text-sm font-medium text-gray-700 mb-1.5">Account Code</label><input v-model="form.account_code" class="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" placeholder="e.g. 50201010" required /></div>
                <div><label class="block text-sm font-medium text-gray-700 mb-1.5">Account Name</label><input v-model="form.account_name" class="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" placeholder="e.g. Office Supplies Expense" required /></div>
                <div><label class="block text-sm font-medium text-gray-700 mb-1.5">Account Title</label><input v-model="form.particular" class="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" placeholder="e.g. Paper & Ink Supplies" required /></div>
                <div><label class="block text-sm font-medium text-gray-700 mb-1.5">Description</label><input v-model="form.description" class="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" placeholder="Optional notes" /></div>
            </div>
            <div class="flex items-center justify-end gap-3 pt-5 border-t mt-4">
                <button type="button" @click="showModal = false" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition">Cancel</button>
                <button type="submit" :disabled="form.processing" class="rounded-lg bg-navy-dark px-5 py-2 text-sm font-semibold text-white hover:bg-navy transition shadow-sm">{{ form.processing ? 'Saving...' : (editing ? 'Update' : 'Save Account Title') }}</button>
            </div>
        </form>
    </Modal>
</AppLayout>
</template>
