// components/dashboard.tsx
"use client"

import { useBudget } from "@/lib/budget-context"
import { formatCurrency } from "@/lib/store"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import {
  Wallet,
  TrendingDown,
  PiggyBank,
  FileText,
  CreditCard,
  BarChart3,
} from "lucide-react"
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts"
import Image from "next/image"

const COLORS = ["#1a2744", "#d4a843", "#2c5282", "#8b6914", "#4a6fa5"]

export function Dashboard() {
  const { budgets, categories, expenses, disbursements } = useBudget()

  const currentBudget = budgets.find((b) => b.year === 2025)
  const totalAppropriation = currentBudget
    ? currentBudget.items.reduce((sum, item) => sum + item.appropriation, 0)
    : 0
  const totalExpenditure = currentBudget
    ? currentBudget.items.reduce((sum, item) => sum + item.expenditure, 0)
    : 0
  const totalBalance = totalAppropriation - totalExpenditure
  const utilizationRate = totalAppropriation > 0 ? (totalExpenditure / totalAppropriation) * 100 : 0

  const pendingExpenses = expenses.filter((e) => e.status === "pending").length
  const pendingDisbursements = disbursements.filter((d) => d.status === "pending").length

  const categoryData = categories.map((cat) => {
    const catItems = currentBudget?.items.filter((i) => i.categoryId === cat.id) || []
    const appropriation = catItems.reduce((s, i) => s + i.appropriation, 0)
    const expenditure = catItems.reduce((s, i) => s + i.expenditure, 0)
    return {
      name: cat.name.length > 15 ? cat.name.slice(0, 15) + "..." : cat.name,
      fullName: cat.name,
      Appropriation: appropriation,
      Expenditure: expenditure,
    }
  }).filter((d) => d.Appropriation > 0)

  const pieData = categories.map((cat) => {
    const catItems = currentBudget?.items.filter((i) => i.categoryId === cat.id) || []
    const value = catItems.reduce((s, i) => s + i.appropriation, 0)
    return { name: cat.name, value }
  }).filter((d) => d.value > 0)

  return (
    <div className="space-y-6">
      {/* Hero Section with Logo */}
      <div className="flex items-center gap-4">
        <Image
          src="/images/logo.jpg"
          alt="MMACI Logo"
          width={64}
          height={64}
          className="rounded-full border-2 border-[#d4a843] shadow-lg"
        />
        <div>
          <h2 className="text-2xl font-bold text-[#1a2744]">Dashboard</h2>
          <p className="text-sm text-muted-foreground">
            Budget & Funds Utilization Overview - FY 2025-2026
          </p>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card className="border-l-4 border-l-[#1a2744]">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Appropriation
            </CardTitle>
            <Wallet className="h-4 w-4 text-[#1a2744]" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-[#1a2744]">
              {formatCurrency(totalAppropriation)}
            </div>
            <p className="text-xs text-muted-foreground">FY 2025 Budget</p>
          </CardContent>
        </Card>

        <Card className="border-l-4 border-l-[#d4a843]">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Expenditure
            </CardTitle>
            <TrendingDown className="h-4 w-4 text-[#d4a843]" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-[#1a2744]">
              {formatCurrency(totalExpenditure)}
            </div>
            <p className="text-xs text-[#d4a843] font-semibold">
              {utilizationRate.toFixed(1)}% utilized
            </p>
          </CardContent>
        </Card>

        <Card className="border-l-4 border-l-[#2c5282]">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Remaining Balance
            </CardTitle>
            <PiggyBank className="h-4 w-4 text-[#2c5282]" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-[#1a2744]">
              {formatCurrency(totalBalance)}
            </div>
            <p className="text-xs text-muted-foreground">
              {(100 - utilizationRate).toFixed(1)}% remaining
            </p>
          </CardContent>
        </Card>

        <Card className="border-l-4 border-l-red-500">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Pending Approvals
            </CardTitle>
            <FileText className="h-4 w-4 text-red-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-[#1a2744]">
              {pendingExpenses + pendingDisbursements}
            </div>
            <p className="text-xs text-muted-foreground">
              {pendingExpenses} expenses, {pendingDisbursements} disbursements
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Utilization Progress */}
      <Card>
        <CardHeader className="bg-[#1a2744] rounded-t-lg">
          <CardTitle className="text-base text-white">Budget Utilization Rate</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 pt-4">
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Overall Utilization</span>
            <span className="font-semibold text-[#1a2744]">{utilizationRate.toFixed(1)}%</span>
          </div>
          <Progress value={utilizationRate} className="h-3" />
          <div className="grid gap-3 pt-2 md:grid-cols-2 lg:grid-cols-3">
            {categories.map((cat) => {
              const items = currentBudget?.items.filter((i) => i.categoryId === cat.id) || []
              const approp = items.reduce((s, i) => s + i.appropriation, 0)
              const expend = items.reduce((s, i) => s + i.expenditure, 0)
              const rate = approp > 0 ? (expend / approp) * 100 : 0
              if (approp === 0) return null
              return (
                <div key={cat.id} className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <span className="truncate text-muted-foreground">{cat.name}</span>
                    <span className="font-medium text-[#1a2744]">{rate.toFixed(1)}%</span>
                  </div>
                  <Progress value={rate} className="h-2" />
                </div>
              )
            })}
          </div>
        </CardContent>
      </Card>

      {/* Charts */}
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader className="flex flex-row items-center gap-2 bg-[#1a2744] rounded-t-lg">
            <BarChart3 className="h-5 w-5 text-[#d4a843]" />
            <CardTitle className="text-base text-white">Appropriation vs Expenditure</CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={categoryData} margin={{ top: 5, right: 10, left: 10, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis
                    dataKey="name"
                    tick={{ fontSize: 10, fill: "#64748b" }}
                    angle={-20}
                    textAnchor="end"
                    height={60}
                  />
                  <YAxis
                    tick={{ fontSize: 10, fill: "#64748b" }}
                    tickFormatter={(v) => `${(v / 1000000).toFixed(1)}M`}
                  />
                  <Tooltip
                    formatter={(value: number) => formatCurrency(value)}
                    contentStyle={{
                      backgroundColor: "#fff",
                      border: "1px solid #e2e8f0",
                      borderRadius: "6px",
                      fontSize: "12px",
                    }}
                  />
                  <Bar dataKey="Appropriation" fill="#1a2744" radius={[4, 4, 0, 0]} />
                  <Bar dataKey="Expenditure" fill="#d4a843" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center gap-2 bg-[#1a2744] rounded-t-lg">
            <CreditCard className="h-5 w-5 text-[#d4a843]" />
            <CardTitle className="text-base text-white">Budget Allocation by Category</CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={pieData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={100}
                    paddingAngle={3}
                    dataKey="value"
                  >
                    {pieData.map((_, idx) => (
                      <Cell key={idx} fill={COLORS[idx % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip
                    formatter={(value: number) => formatCurrency(value)}
                    contentStyle={{
                      backgroundColor: "#fff",
                      border: "1px solid #e2e8f0",
                      borderRadius: "6px",
                      fontSize: "12px",
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="mt-2 flex flex-wrap gap-3">
              {pieData.map((entry, idx) => (
                <div key={entry.name} className="flex items-center gap-1.5 text-xs">
                  <div
                    className="h-2.5 w-2.5 rounded-full"
                    style={{ backgroundColor: COLORS[idx % COLORS.length] }}
                  />
                  <span className="text-muted-foreground">{entry.name}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Recent Activity */}
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader className="bg-[#1a2744] rounded-t-lg">
            <CardTitle className="text-base text-white">Recent Expenses</CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="space-y-3">
              {expenses.slice(0, 4).map((exp) => (
                <div key={exp.id} className="flex items-center justify-between rounded border border-border p-3">
                  <div>
                    <p className="text-sm font-medium text-[#1a2744]">{exp.refNo}</p>
                    <p className="text-xs text-muted-foreground">{exp.description}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm font-semibold text-[#1a2744]">{formatCurrency(exp.amount)}</p>
                    <span
                      className={`inline-block rounded-full px-2 py-0.5 text-xs font-medium ${
                        exp.status === "approved"
                          ? "bg-green-100 text-green-700"
                          : exp.status === "pending"
                          ? "bg-[#d4a843]/15 text-[#8b6914]"
                          : "bg-red-100 text-red-700"
                      }`}
                    >
                      {exp.status.charAt(0).toUpperCase() + exp.status.slice(1)}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="bg-[#1a2744] rounded-t-lg">
            <CardTitle className="text-base text-white">Recent Disbursements</CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="space-y-3">
              {disbursements.slice(0, 4).map((dsb) => (
                <div key={dsb.id} className="flex items-center justify-between rounded border border-border p-3">
                  <div>
                    <p className="text-sm font-medium text-[#1a2744]">{dsb.disbursementNo}</p>
                    <p className="text-xs text-muted-foreground">{dsb.description} - {dsb.payTo}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm font-semibold text-[#1a2744]">{formatCurrency(dsb.amount)}</p>
                    <span
                      className={`inline-block rounded-full px-2 py-0.5 text-xs font-medium ${
                        dsb.status === "posted"
                          ? "bg-blue-100 text-blue-700"
                          : dsb.status === "approved"
                          ? "bg-green-100 text-green-700"
                          : dsb.status === "pending"
                          ? "bg-[#d4a843]/15 text-[#8b6914]"
                          : "bg-red-100 text-red-700"
                      }`}
                    >
                      {dsb.status.charAt(0).toUpperCase() + dsb.status.slice(1)}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// resources/js/Pages/Dashboard.vue
<script setup>
import AppLayout from '@/Layouts/AppLayout.vue'
import { Head } from '@inertiajs/vue3'
import { computed } from 'vue'

const props = defineProps({
    budgets: Array,
    stats: Object,
    categoryStats: Array,
    recentExpenses: Array,
    recentDisbursements: Array,
    latestYear: Number,
})

function fmt(v) { return new Intl.NumberFormat('en-PH', { minimumFractionDigits: 2 }).format(v || 0) }
function fmtDate(d) { return d ? new Date(d).toLocaleDateString('en-PH', { year:'numeric', month:'short', day:'numeric' }) : '—' }

const overallUtil = computed(() => {
    if (!props.stats?.totalAppropriation || props.stats.totalAppropriation === 0) return 0
    return (props.stats.totalExpenditure / props.stats.totalAppropriation * 100).toFixed(1)
})

const pendingTotal = computed(() => (props.stats?.pendingExpenses || 0) + (props.stats?.pendingDisbursements || 0))

const barColors = ['#243352', '#d4a843', '#2c3e5e', '#1a2744', '#e0be6a']

const statusColors = {
    pending: 'bg-yellow-100 text-yellow-800',
    approved: 'bg-green-100 text-green-800',
    posted: 'bg-blue-100 text-blue-800',
    cancelled: 'bg-red-100 text-red-800',
}

// Compute max appropriation for bar chart scaling
const maxBarVal = computed(() => {
    if (!props.categoryStats?.length) return 1
    return Math.max(...props.categoryStats.map(c => Math.max(c.appropriation, c.expenditure))) || 1
})
</script>

<template>
<Head title="Dashboard" />
<AppLayout>
    <!-- Page Header -->
    <div class="flex items-center gap-3 mb-6">
        <img src="/images/logo.jpg" alt="" class="h-10 w-10 object-cover border border-mustard/40" />
        <div>
            <h2 class="text-xl font-bold text-gray-900">Dashboard</h2>
            <p class="text-sm text-gray-500">Budget & Funds Utilization Overview — FY {{ latestYear || new Date().getFullYear() }}</p>
        </div>
    </div>

    <!-- 4 Summary Cards -->
    <div class="grid gap-4 md:grid-cols-4 mb-6">
        <div class="bg-white border border-gray-200 overflow-hidden">
            <div class="h-1 bg-navy-dark"></div>
            <div class="p-4">
                <div class="flex items-center justify-between mb-1">
                    <p class="text-[11px] font-bold uppercase tracking-wider text-gray-500">Total Appropriation</p>
                    <span class="text-gray-400"></span>
                </div>
                <p class="text-xl font-bold text-gray-900">{{ fmt(stats?.totalAppropriation) }}</p>
                <p class="text-[11px] text-gray-400 mt-0.5">FY {{ latestYear }} Budget</p>
            </div>
        </div>
        <div class="bg-white border border-gray-200 overflow-hidden">
            <div class="h-1 bg-red-500"></div>
            <div class="p-4">
                <div class="flex items-center justify-between mb-1">
                    <p class="text-[11px] font-bold uppercase tracking-wider text-gray-500">Total Expenditure</p>
                    <span class="text-gray-400"></span>
                </div>
                <p class="text-xl font-bold text-gray-900">{{ fmt(stats?.totalExpenditure) }}</p>
                <p class="text-[11px] text-red-400 mt-0.5">{{ overallUtil }}% utilized</p>
            </div>
        </div>
        <div class="bg-white border border-gray-200 overflow-hidden">
            <div class="h-1 bg-green-500"></div>
            <div class="p-4">
                <div class="flex items-center justify-between mb-1">
                    <p class="text-[11px] font-bold uppercase tracking-wider text-gray-500">Remaining Balance</p>
                    <span class="text-gray-400"></span>
                </div>
                <p class="text-xl font-bold text-gray-900">{{ fmt(stats?.balance) }}</p>
                <p class="text-[11px] text-green-500 mt-0.5">{{ (100 - overallUtil).toFixed(1) }}% remaining</p>
            </div>
        </div>
        <div class="bg-white border border-gray-200 overflow-hidden">
            <div class="h-1 bg-mustard"></div>
            <div class="p-4">
                <div class="flex items-center justify-between mb-1">
                    <p class="text-[11px] font-bold uppercase tracking-wider text-gray-500">Pending Approvals</p>
                    <span class="text-gray-400"></span>
                </div>
                <p class="text-xl font-bold text-gray-900">{{ pendingTotal }}</p>
                <p class="text-[11px] text-gray-400 mt-0.5">{{ stats?.pendingExpenses }} expenses, {{ stats?.pendingDisbursements }} disbursements</p>
            </div>
        </div>
    </div>

    <!-- Budget Utilization Rate -->
    <div class="bg-white border border-gray-200 overflow-hidden mb-6">
        <div class="bg-navy-dark px-5 py-3">
            <h3 class="text-sm font-bold text-white">Budget Utilization Rate</h3>
        </div>
        <div class="p-5">
            <!-- Overall -->
            <div class="mb-5">
                <div class="flex justify-between items-center mb-1.5">
                    <span class="text-sm text-gray-700">Overall Utilization</span>
                    <span class="text-sm font-bold text-gray-900">{{ overallUtil }}%</span>
                </div>
                <div class="w-full h-3 bg-gray-200">
                    <div class="h-full bg-navy-dark transition-all" :style="{ width: Math.min(100, overallUtil) + '%' }"></div>
                </div>
            </div>
            <!-- Per-category bars -->
            <div v-if="categoryStats?.length" class="grid gap-3 md:grid-cols-2">
                <div v-for="(cat, i) in categoryStats" :key="cat.name">
                    <div class="flex justify-between items-center mb-1">
                        <span class="text-xs font-bold uppercase text-gray-600">{{ cat.name }}</span>
                        <span class="text-xs font-bold text-gray-900">{{ cat.utilization }}%</span>
                    </div>
                    <div class="w-full h-2.5 bg-gray-200">
                        <div class="h-full transition-all" :style="{ width: Math.min(100, cat.utilization) + '%', backgroundColor: barColors[i % barColors.length] }"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Two Charts Row: Appropriation vs Expenditure + Budget Allocation by Category -->
    <div class="grid gap-4 md:grid-cols-2 mb-6">
        <!-- Bar Chart: Appropriation vs Expenditure -->
        <div class="bg-white border border-gray-200 overflow-hidden">
            <div class="bg-navy-dark px-5 py-3">
                <h3 class="text-sm font-bold text-white">📊 Appropriation vs Expenditure</h3>
            </div>
            <div class="p-5">
                <div v-if="categoryStats?.length" class="space-y-4">
                    <div v-for="cat in categoryStats" :key="cat.name" class="space-y-1">
                        <p class="text-[10px] font-bold uppercase text-gray-500">{{ cat.name }}</p>
                        <div class="flex items-center gap-2">
                            <div class="flex-1 h-4 bg-gray-100 relative">
                                <div class="absolute inset-y-0 left-0 bg-navy-dark" :style="{ width: (cat.appropriation / maxBarVal * 100) + '%' }"></div>
                            </div>
                            <span class="text-[10px] w-16 text-right font-mono text-gray-600">{{ fmt(cat.appropriation) }}</span>
                        </div>
                        <div class="flex items-center gap-2">
                            <div class="flex-1 h-4 bg-gray-100 relative">
                                <div class="absolute inset-y-0 left-0 bg-mustard" :style="{ width: (cat.expenditure / maxBarVal * 100) + '%' }"></div>
                            </div>
                            <span class="text-[10px] w-16 text-right font-mono text-gray-600">{{ fmt(cat.expenditure) }}</span>
                        </div>
                    </div>
                    <div class="flex items-center gap-4 pt-2 border-t text-[10px] text-gray-500">
                        <span class="flex items-center gap-1"><span class="inline-block w-3 h-3 bg-navy-dark"></span> Appropriation</span>
                        <span class="flex items-center gap-1"><span class="inline-block w-3 h-3 bg-mustard"></span> Expenditure</span>
                    </div>
                </div>
                <p v-else class="text-center text-gray-400 py-8">No data</p>
            </div>
        </div>

        <!-- Donut-style allocation chart -->
        <div class="bg-white border border-gray-200 overflow-hidden">
            <div class="bg-navy-dark px-5 py-3">
                <h3 class="text-sm font-bold text-white">📁 Budget Allocation by Category</h3>
            </div>
            <div class="p-5">
                <div v-if="categoryStats?.length">
                    <!-- Visual allocation bars -->
                    <div class="space-y-3 mb-4">
                        <div v-for="(cat, i) in categoryStats" :key="cat.name">
                            <div class="flex justify-between text-xs mb-1">
                                <span class="font-medium text-gray-700">{{ cat.name }}</span>
                                <span class="font-bold">{{ fmt(cat.appropriation) }}</span>
                            </div>
                            <div class="w-full h-3 bg-gray-100">
                                <div class="h-full transition-all" :style="{ width: (stats?.totalAppropriation > 0 ? cat.appropriation / stats.totalAppropriation * 100 : 0) + '%', backgroundColor: barColors[i % barColors.length] }"></div>
                            </div>
                        </div>
                    </div>
                    <!-- Legend -->
                    <div class="flex flex-wrap gap-3 pt-3 border-t">
                        <span v-for="(cat, i) in categoryStats" :key="cat.name" class="flex items-center gap-1 text-[10px] text-gray-600">
                            <span class="inline-block w-2.5 h-2.5" :style="{ backgroundColor: barColors[i % barColors.length] }"></span>
                            {{ cat.name }}
                        </span>
                    </div>
                </div>
                <p v-else class="text-center text-gray-400 py-8">No data</p>
            </div>
        </div>
    </div>

    <!-- Recent Expenses & Disbursements -->
    <div class="grid gap-4 md:grid-cols-2 mb-6">
        <!-- Recent Expenses -->
        <div class="bg-white border border-gray-200 overflow-hidden">
            <div class="bg-navy-dark px-5 py-3">
                <h3 class="text-sm font-bold text-white">Recent Expenses</h3>
            </div>
            <div class="divide-y">
                <div v-for="e in recentExpenses" :key="e.id" class="px-5 py-3 flex items-center justify-between">
                    <div>
                        <p class="text-sm font-bold text-gray-900">{{ e.ref_no }}</p>
                        <p class="text-xs text-gray-500">{{ e.category?.name }}</p>
                    </div>
                    <div class="text-right">
                        <p class="text-sm font-bold text-gray-900">{{ fmt(e.amount) }}</p>
                        <span :class="[statusColors[e.status], 'inline-block px-2 py-0.5 text-[10px] font-bold uppercase']">{{ e.status }}</span>
                    </div>
                </div>
                <div v-if="!recentExpenses?.length" class="px-5 py-6 text-center text-gray-400 text-sm">No recent expenses</div>
            </div>
        </div>

        <!-- Recent Disbursements -->
        <div class="bg-white border border-gray-200 overflow-hidden">
            <div class="bg-navy-dark px-5 py-3">
                <h3 class="text-sm font-bold text-white">Recent Disbursements</h3>
            </div>
            <div class="divide-y">
                <div v-for="d in recentDisbursements" :key="d.id" class="px-5 py-3 flex items-center justify-between">
                    <div>
                        <p class="text-sm font-bold text-gray-900">{{ d.disbursement_no }}</p>
                        <p class="text-xs text-gray-500">{{ d.description }} — {{ d.pay_to }}</p>
                    </div>
                    <div class="text-right">
                        <p class="text-sm font-bold text-gray-900">{{ fmt(d.amount) }}</p>
                        <span :class="[statusColors[d.status], 'inline-block px-2 py-0.5 text-[10px] font-bold uppercase']">{{ d.status }}</span>
                    </div>
                </div>
                <div v-if="!recentDisbursements?.length" class="px-5 py-6 text-center text-gray-400 text-sm">No recent disbursements</div>
            </div>
        </div>
    </div>
</AppLayout>
</template>
